{ pkgs, lib, ... }:
{
    imports = [
        ./gui
        ./shell
        ./terminal
        ./wm
        ./cursors
    ];
    fonts.fontconfig.enable = true;
    home.packages = with pkgs; [
        # keep-sorted start
        alsa-lib
        audacity
        bear
        blueman
        brave
        brightnessctl
        clang-tools
        cliphist
        cmake
        curl
        curl.dev
        kdePackages.dolphin
        kdePackages.qt6ct
        libsForQt5.qt5ct
        fd
        ffmpeg
        fzf
        gcc
        glow
        gnumake
        grim
        gtk4-layer-shell
        gtkmm4
        htop
        hyprshade
        imagemagick
        jq
        just
        keep-sorted
        libnotify
        mission-center
        networkmanagerapplet
        nautilus
        nil
        nwg-look
        obs-studio
        openssl
        osu-lazer-bin
        pkg-config
        pkgs.nerd-fonts.ubuntu
#        pkgs.python3Packages.matplotlib
        playerctl
        psmisc
        pyright
        python3
        qt6.qtdeclarative
        qt6.qttools
        ripgrep
        slurp
        spotify
        texstudio
        tree
        tty-clock
        thunar
        unzip
        usbutils
        vim
        wev
        wf-recorder
        wl-clipboard
        wl-gammactl
        xev
        yq
        yt-dlp
        # keep-sorted end
    ];
}
