local general       = require("general")
local binds         = require("binds")
local animations    = require("animations")
local monitors      = require("monitors")
local input         = require("input")
local init          = require("autostart")
local env           = require("env")
local wr            = require("windowrules")

general.init()
binds.init()
animations.init()
monitors.init()
input.init()
env.init()
wr.init()

hl.on("hyprland.start", init.init)
