on:
  push:
    branches:
      - main

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - run: nix develop --command bash -c "find . -name '*.nix' | xargs keep-sorted"
      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git diff --staged --quiet || git commit -m "chore: keep-sorted"
          git push
